---

language: python
cache: pip

env:
  - ANSIBLE_VERSION=2.8.15
  - ANSIBLE_VERSION=2.9.14
  - ANSIBLE_VERSION=latest

install:
  - if [ "${ANSIBLE_VERSION}" = "latest" ]; then pip3 install -U ansible ansible-lint; else pip3 install -U ansible==${ANSIBLE_VERSION} ansible-lint; fi

script:
  - ansible-lint --version
  - ansible-lint -v .
  - ansible --version
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check -e 'ansible_python_interpreter=/usr/bin/python3'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
