---
- name: "Ensure that proxy available"
  uri:
    url: "{{ proxy_url }}"
    method: CONNECT
    status_code: 500
    timeout: 2
  when: proxy_url != ''

- name: "Add IUS repository"
  become: true
  template:
    src: "{{ item }}"
    dest: "{{ ius_repo_files_path }}/{{ item }}"
  with_items:
    - "ius.repo"
    - "ius-testing.repo"
    - "ius-dev.repo"
    - "ius-archive.repo"
  register: ius_templates

- name: "Update yum cache"
  become: true
  command: "yum makecache"
  args:
    warn: false
  tags:
    - skip_ansible_lint
  when: ius_templates is changed