---
- name: "Ensure proxy is available."
  uri:
    url: "{{ proxy_url }}"
    method: CONNECT
    status_code: 500
    timeout: 2
  when: proxy_url | length > 0

- name: "Add IUS repository."
  become: true
  yum:
    name: "{{ ius_repo_files_path }}/ius-release-el{{ ansible_distribution_major_version }}.rpm"
  register: ius_repo

- name: "Update yum cache."
  become: true
  command: "yum makecache"
  args:
    warn: false
  tags:
    - skip_ansible_lint
  when: ius_repo is changed
