---
- name: "Ensure proxy is available."
  uri:
    url: "{{ proxy_url }}"
    method: CONNECT
    status_code: 500
    timeout: 2
  when: proxy_url | length > 0

- name: "Add IUS release repository."
  become: true
  yum:
    name: "{{ iius_repo_url }}/ius-release-el{{ ansible_distribution_major_version }}.rpm"
  register: ius_repo
  when: ius_enable

- name: "Add IUS testing repository."
  become: true
  yum:
    name: "{{ iius_repo_url }}/ius-testing-{{ ansible_distribution_major_version }}.rpm"
  register: ius_testing
  when: ius_enable_testing

- name: "Add IUS testing repository."
  become: true
  yum:
    name: "{{ iius_repo_url }}/ius-testing-{{ ansible_distribution_major_version }}.rpm"
  register: ius_testing
  when: ius_enable_archive

- name: "Update yum cache."
  become: true
  command: "yum makecache"
  args:
    warn: false
  tags:
    - skip_ansible_lint
  when: ius_repo is changed
